server:
  port: 7999
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*" # spring boot2.4配置
            # allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        - id: personalInfo
          uri: lb://personalInfo
          predicates:
            - Path=/person/**
        - id: notice
          uri: lb://notice
          predicates:
            - Path=/notice/**
        - id: experiment
          uri: lb://experiment
          predicates:
            - Path=/experiment/**
        - id: course
          uri: lb://course
          predicates:
            - Path=/course/**
        - id: login
          uri: lb://login
          predicates:
            - Path=/login/**
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
        - id: report
          uri: lb://report
          predicates:
            - Path=/report/**
        - id: resource
          uri: lb://resource
          predicates:
            - Path=/resource/**
        - id: grade
          uri: lb://grade
          predicates:
            - Path=/grade/**
  main:
    web-application-type: reactive


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
