server:
  port: 7999
spring:
  application:
    name: gateway
  cloud:
    gateway:

      routes:
        - id: personalInfo
          uri: lb://personalInfo
          predicates:
            - Path=/person/**
        - id: notice
          uri: lb://notice
          predicates:
            - Path=/notice/**
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
  main:
    web-application-type: reactive


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
