server:
  port: 8088
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123abc
      url: jdbc:mysql://123.60.156.14:3306/db_grade?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  application:
    name: grade

logging:
  charset:
    console: UTF-8
  level:
    sql: debug
    root: info
    web: info
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
