server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    druid:
      connect-timeout: 100
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123abc
      url: jdbc:mysql://123.60.156.14:3306/db_etms2?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  application:
    name: admin


logging:
  level:
    root: debug
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST}
  client:
    service-url:
      defaultZone: http://123.60.156.14:8080/eureka



