server:
  port: 8082

spring:
  datasource:
    druid:
      connect-timeout: 100
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123abc
      url: jdbc:mysql://123.60.156.14:3306/db_notice?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  application:
    name: notice


logging:
  level:
    root: debug
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST}
  client:
    service-url:
      defaultZone: http://123.60.156.14:8080/eureka

aliyun:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAI5tM8Q255sUYhQtuP6H5y
  accessKeySecret: CRW2Uv49TDpomgbhvoewRQIt0KFQNb
  bucketName: tj-etms
