server:
  port: 8083

spring:
  datasource:
    druid:
      connect-timeout: 100
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123abc
      url: jdbc:mysql://123.60.156.14:3306/db_experiment_lyf?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  application:
    name: experiment


logging:
  level:
    root: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka



